[project]
name = "v3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "google-generativeai>=0.8.5",
    "pymupdf>=1.26.4",
    "python-dotenv>=1.1.1",
    "pyyaml>=6.0.3",
]
